apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    tier: backend
    layer: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: laravel
  template:
    metadata:
      labels:
        tier: backend
        layer: laravel
    spec:
      initContainers:
        - name: migrations
          image: danielruizluna/laravel-react-todo:v0.0.2
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel
            - secretRef:
                name: laravel
      containers:
      - name: laravel
        image: danielruizluna/laravel-react-todo:v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
        envFrom:
          - configMapRef:
              name: laravel
          - secretRef:
              name: laravel
