apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-nginx
  labels:
    tier: backend
    layer: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: nginx
  template:
    metadata:
      labels:
        tier: backend
        layer: nginx
    spec:
      containers:
        - name: nginx
          image: danielruizluna/nginx-todo:v0.0.1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
