apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-nginx
  labels:
    tier: backend
    layer: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: nginx
  template:
    metadata:
      labels:
        tier: backend
        layer: nginx
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d
